development:
  adapter: postgresql
  database: ticketee_development
  username: vagrant
  pool: 5 
  template: template0

test:
  adapter: postgresql
  database: ticketee_test
  username: vagrant
  pool: 5 
  template: template0

production:
  adapter: postgresql
  database: ticketee_production
  username: vagrant
  pool: 5 
  template: template0
